### ISSUE TITLE
after closing csgo this happened

### ISSUE THREAD

**Issue by anthrax0227** [Jire/Charlatano#874] opened 2019-12-03 06:48 UTC
it says that i should report this so ill be leaving it here. the censored part is my folder thanks for understanding
![image](https://user-images.githubusercontent.com/45764020/70026936-de4f9500-15db-11ea-9224-aa20cab7f026.png)

**Comment by x7airworker** [comment] 2019-12-20 20:10
Which java version do you have?

**Comment by x7airworker** [comment] 2019-12-20 20:11
Duplicate of #869

**Closed** 2019-12-21 09:50 UTC
